[package]
name = "fluid-simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
colorgrad = "0.8.0"
egui-macroquad = "0.17.3"
macroquad = "0.4.14"
rayon = "1.11.0"
rdxsort = "0.3.0"
wgpu = "28.0.0"
